apiVersion: v1
kind: Service
metadata:
  name: mysql-clusterip
  namespace: db-offer-statefulset
spec:
  selector:
    app: db1
  ports:
    - name: mysql
      protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP

