apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod
  name: pod
spec:
  containers:
  - image: ayadinou/offer-svc
    name: pod
    imagePullPolicy: IfNotPresent
  nodeSelector:
    img: here
