apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: ayadinou/auth-svc
          ports:
            - containerPort: 50051
          env:
            - name: HOSTDB
              value: pgpool-svc.database-auth.svc.cluster.local
            - name: PASSDB
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: postgresql-password

