apiVersion: v1
kind: Service
metadata:
  name: mysql-clusterip
  namespace: db-offer-statefulset
spec:
  selector:
    app: mysql
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP

