apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: ayadinou/auth-svc
          ports:
            - containerPort: 50051
          env:
            - name: HOSTDB
              value: mysql-clusterip.db-offer-statefulset.svc.cluster.local
            - name: PASSDB
              value: "123"

