apiVersion: apps/v1
kind: Deployment
metadata:
  name: offer
  namespace: offer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: offer
  template:
    metadata:
      labels:
        app: offer
    spec:
      containers:
        - name: offer
          image: ayadinou/offer-svc
          ports:
            - containerPort: 50053
          env:
            - name: HOSTDB
              value: "mysql-clusterip.db-offer-statefulset.svc.cluster.local"
            - name: PASSDB
              value: "123"

